services:
  munchbox_db:
    image: mysql:8.4.4
    container_name: munchbox_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: munchbox
      MYSQL_DATABASE: munchbox_db
      MYSQL_USER: munchbox
      MYSQL_PASSWORD: munchbox
    ports:
      - "3306:3306"
    volumes:
      - munchbox_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  munchbox_app:
    image: eclipse-temurin:21-jre
    container_name: munchbox_app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://munchbox_db:3306/munchbox_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=munchbox
      - SPRING_DATASOURCE_PASSWORD=munchbox
    depends_on:
      - munchbox_db
    command: ["java", "-jar", "/app/munchbox.jar"]

volumes:
  munchbox_db_data: